#!/usr/bin/python
import MySQLdb
c = MySQLdb.connect('localhost','root','','mikrotik_erp')
c.autocommit(True)
q = c.cursor()

q.execute('SELECT radacctid, username, acctuniqueid '
          'FROM radacct '
          'WHERE acctstoptime IS NULL '
          'GROUP BY username, acctuniqueid HAVING COUNT(*)>1')

for radacctid, username, acctuniqueid in q.fetchall():
    print username, acctuniqueid
    q.execute('DELETE FROM radacct '
              'WHERE username=%s '
              '  AND acctuniqueid=%s '
              '  AND radacctid<>%s '
              '  AND acctstoptime is null', (username, acctuniqueid, radacctid))

